# Generated by Django 4.0.4 on 2022-07-03 09:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=120)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('address', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('12 months to pay', '12 months to pay'), ('24 months to pay', '24 months to pay')], default='24 months to pay', max_length=24)),
                ('amount', models.IntegerField()),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='U', max_length=24)),
                ('date_created', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.debtor')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('debtor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.debtor')),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.loan')),
            ],
        ),
    ]
