# Generated by Django 4.0.4 on 2022-06-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_debtor_loan_payment_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('12 months to pay', '12 months to pay'), ('24 months to pay', '24 months to pay')], max_length=24),
        ),
    ]
