# Generated by Django 4.0.4 on 2022-06-06 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_payment_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='month',
            new_name='month_number',
        ),
    ]
