# Generated by Django 4.0.4 on 2022-06-25 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_rename_month_payment_month_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
