# Generated by Django 4.0.4 on 2022-06-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_loan_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Paid'), ('U', 'Unpaid')], default='U', max_length=2),
        ),
    ]
