# Generated by Django 4.0.4 on 2022-06-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_alter_loan_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('12 months to pay', '12 months to pay'), ('24 months to pay', '24 months to pay')], default='24 months to pay', max_length=24),
        ),
    ]
